### ISSUE TITLE
Implement `--sort-keys`

### ISSUE THREAD

**Issue by xduugu** [01mf02/jaq#149]
Sorting the keys is quite useful, e.g. when comparing two json files.

```
    --sort-keys / -S:

Output the fields of each object with the keys in sorted order.
```

**Comment by 01mf02** [comment]
I understand the usefulness of sorting keys, but this functionality could be equally well implemented as a filter.

What do you think about including the following definition in jaq?

~~~ jq
def sort_keys: walk(if isobject then to_entries | sort_by(.key) | from_entries end);
~~~

That would allow you to replace `jq --sort-keys 'f'` by `jaq 'f | sort_keys'`.

**Comment by 01mf02** [comment]
I just realised that `to_entries` already sorts by key. That means that we can get away by writing simply:

~~~ jq
def sort_keys: walk(if isobject then to_entries | from_entries end);
~~~

We can make that more performant by unfolding `*_entries`:

~~~ jq
def sort_keys: walk(if isobject then [keys[] as $k | { ($k): .[$k] }] | add + {} end)
~~~

Unfolding `add` allows us to save one array:

~~~ jq
def sort_keys: walk(if isobject then reduce (keys[] as $k | { ($k): .[$k] }) as $o ({}; . + $o) end);
~~~

And that's probably how fast it gets when doing it by definition.

Testing:

~~~
jaq -n 'def sort_keys: walk(if isobject then reduce (keys[] as $k | { ($k): .[$k] }) as $o ({}; . + $o) end); {c: {b: 1, a: 2}, a: 1, b: {}} | sort_keys'
{
  "a": 1,
  "b": {},
  "c": {
    "a": 2,
    "b": 1
  }
}
~~~

**Comment by xduugu** [comment]
@01mf02 Implementing it as a filter instead of a commandline option would be fine for me, thanks! As far as I know, jq only supports the `--sort-keys` options, that's why I proposed it.

> I just realised that to_entries already sorts by key. That means that we can get away by writing simply:

Is this on purpose? I ask because jq explicitly does **not** sort the keys since commit https://github.com/jqlang/jq/commit/4a57b84db03db7aee33c47ed6c7f6c1e648705fd.

**Comment by pkoppstein** [comment]
@01mf02 wrote:
> I just realised that to_entries already sorts by key. 


If so, that is (or should be considered) a bug.

**Comment by 01mf02** [comment]
> Is this on purpose? I ask because jq explicitly does **not** sort the keys since commit [jqlang/jq@4a57b84](https://github.com/jqlang/jq/commit/4a57b84db03db7aee33c47ed6c7f6c1e648705fd).

No, that was not on purpose. 484dd27 should now correct this.

@pkoppstein, what would you think about including the proposed `sort_keys` in jq? This would make it possible to express sorting by keys the same way in both jaq and jq.

**Comment by pkoppstein** [comment]
@01mf02 asked:
> what would you think about including the proposed sort_keys in jq? This would make it possible to express sorting by keys the same way in both jaq and jq.

My only strong preference regarding these matters is that jaq's `to_entries` closely tracks jq's, so thank you for https://github.com/01mf02/jaq/commit/484dd270a084ee7e6f233c781f96444264af530b

It may, however, be of interest to know that some of the jq maintainers have a strong distaste for command-line options and seem only to retain -S mainly for the sake of backwards compatibility. In this particular case,
since the proposed `sort_keys` is trivial to implement in jq, I would tend to regard it as unnecessary bloat.  There are certainly other functions higher on my priority list for adding to the standard "built-ins".  

Another consideration is that if jaq defines sort_keys before jq, then that will introduce a discrepancy and hence add confusion and noise.

**Comment by Freed-Wu** [comment]
Can we support -S for compatibility of jq, then wait #3012?

**Comment by 01mf02** [comment]
@Freed-Wu, @xduugu, after some reflection, I added `--sort-keys` after all to jaq 05f43ed71ce6e4d5269a83f5fef9a28373d59005. The reason behind this is that `--sort-keys` is more performant than running an equivalent filter before printing. That is because `--sort-keys` sorts only once it encounters an object, whereas an equivalent filter has to sort everything before printing the least part of a value.

**Comment by xduugu** [comment]
That was unexpected. :star_struck: I just tested jaq 2.0 and it works great. Thanks a lot, @01mf02!
