### ISSUE TITLE
Support JQ's index/rindex function

### ISSUE THREAD

**Issue by John-Toohey** [01mf02/jaq#154]
Jq has the [`index`](https://jqlang.github.io/jq/manual/#index-rindex) and `rindex` functions which don't seem to be supported in jaq.  Is there a specific reason for this?  Thank you for your time.

**Comment by kklingenberg** [comment]
I don't think it's intentional. I'd even guess that anything from jq that's purposely excluded from jaq is documented in the README. For these filters (`indices`, `index`, `rindex`) you could just implement them in [std](https://github.com/01mf02/jaq/blob/main/jaq-std/src/std.jq). This is my attempt at it, using two auxiliary filters to deal with iterating over strings, and windowing:

```jq
# Indexing
def indices($i):
  def enumerate:
    . as $thing |
    if type == "string"
    then range(length) | [., $thing[.:.+1]]
    else range(length) | [., $thing[.]]
    end;

  def windowed($size):
    if $size <= 0 then empty
    else . as $array | range(length - $size + 1) | $array[.:. + $size]
    end;

  if ["string", "array"] | any(. == ($i | type))
  then [[windowed($i | length)] | enumerate | select(.[1] == $i)[0]]
  else [enumerate | select(.[1] == $i)[0]]
  end;

def index($i):  indices($i) | .[0];
def rindex($i): indices($i) | .[-1:][0];
```

It's not very good, and fails on `["a", "b", "c"] | indices("b")` (mostly because of incomplete type dispatching), but it could be a start.

**Comment by kklingenberg** [comment]
I fixed the error by changing the condition to `if ($i | type) == "array" or (type == "string" and ($i | type) == "string")`, based on `[jq's` implementation](https://github.com/jqlang/jq/blob/13e02ba348b51b60350d142ab16f2ac6f4e5967a/src/builtin.jq#L45-L48). Then I realized that jq gives special meaning to array as indices as in `[1,2][[1,2]]`. jaq doesn't allow that :thinking:. _That_ is probably intentionally not supported :sweat_smile: 

Anyway I put my implementation of these filters in a PR, with tests copied straight from jq's website:  #158
