### ISSUE TITLE
jq difference of Cartesian product iterating order

### ISSUE THREAD

**Issue by itchyny** [01mf02/jaq#17]
Due to the difference of iterating Cartesian product, currently `jaq` yields different order.
```
 $ jq -n '(1,2) * (3,4)'
3
6
4
8
 $ jaq -n '(1,2) * (3,4)'
3
4
6
8
```

**Comment by 01mf02** [comment]
Nice catch! :)
However, the way the jq handles Cartesian products is not consistent, IMHO --- consider:

~~~
$ jq -n '[{a: (0,1), b: (2,3)}] | .[] | .a * .b'
0 0 2 3
~~~

~~~
$ jq -n '(0,1) * (2,3)'
0 2 0 3
~~~

In both cases, a Cartesian product is built, but for some weird reason, the Cartesian product for objects does not have the same order as for mathematical operations.
Given that, I have opted for jaq to adapt one consistent Cartesian product order --- and the object one turned out to be easier to implement.
However, I did not document this so far. I will write a test for this explaining the reason.

**Comment by 01mf02** [comment]
I now wrote a test for this in 50184ac76db411c5cba55a275b31e5f889c82005

**Comment by itchyny** [comment]
This is just for reference but I have to mention the arguments evaluation difference between jq-coded and internal filters in jq, since you might find this interesting.
```
 $ jq -n 'range((1,2|debug); (3,4|debug))' # jq-coded filter
["DEBUG:",1]
["DEBUG:",3]
["DEBUG:",4]
["DEBUG:",2]
["DEBUG:",3]
["DEBUG:",4]
1
2
1
2
3
2
2
3

 $ jq -n 'fmax((1,2|debug); (3,4|debug))' # internal filter
["DEBUG:",3]
["DEBUG:",1]
["DEBUG:",2]
["DEBUG:",4]
["DEBUG:",1]
["DEBUG:",2]
3
3
4
4
```
Binomial operators are compiled to internal filters with  2-arity, so the right hand side are evaluated first (unlike many other programming languages; due to purity of jq most users do not aware of this ordering).
```
 $ jq -n '(1,2|debug) * (3,4|debug)'
["DEBUG:",3]
["DEBUG:",1]
["DEBUG:",2]
["DEBUG:",4]
["DEBUG:",1]
["DEBUG:",2]
3
6
4
8
```
This evaluation order difference originates from the evaluation order of calling filter vs evaluating arguments.
For internal filters, `jq` evaluates arguments backwards and then call the filter, but for jq-coded filters it first call the filter and evaluates the argument closures forwards.
If `jaq` starts to implement mathematical filters with 2-arity (like `fmax`), the order will be different from `jq` just like operators.

**Comment by 01mf02** [comment]
Thanks for pointing this out, @itchyny!
