### ISSUE TITLE
Invalid link in README.md

### ISSUE THREAD

**Issue by emanuele6** [01mf02/jaq#194]
This link in `README.md` points to <https://github.com/01mf02/jaq/blob/main/entrust>, that is a file that does not exist in the repository:
https://github.com/01mf02/jaq/blob/3d75869c7913f9b1a61a102f270defdab43c864b/README.md?plain=1#L737

It was probably meant to point somewhere else.

**Comment by emanuele6** [comment]
I've just found the same text at the bottom of <https://nlnet.nl/project/jaq/>; it was supposed to link to <https://nlnet.nl/entrust/>.

**Comment by wader** [comment]
Didn't know jag has received funding, congrats 🥳

**Comment by wader** [comment]
I wonder if it could be interesting for jq itself? i don't need any extra monies but maybe some other maintainer or other person could be interested? wonder how much administrational work it involves?

**Comment by 01mf02** [comment]
@emanuele6, thanks for spotting this! I have corrected the link now.

@wader, thanks! From my experience, the administrational work involved with obtaining this grant has been pleasantly little, but on the other hand, you should not be in a hurry, because NLnet can often take some time to respond (they manage quite many projects, after all).
