### ISSUE TITLE
JSON with Comments (jsonc) support

### ISSUE THREAD

**Issue by denosaurtrain** [01mf02/jaq#197]
### Feature/Workaround Request

Request: an option to make `jaq` ignore comments in input like this:

```jsonc
{
    /*
       block comment
    */
    "a": true // line comment
}
```

Today, `jaq . file.json` fails with this error:

> Error: failed to parse: string expected

If this is considered a "Won't Fix", any suggestions for workarounds?

### What is jsonc, and who cares?

```diff
@@ 👇 clarification based on discussion in comments @@

- Some tools allow comments in JSON files, sometimes called "JSON with Comments" or "jsonc"
+ The format of comments described above is "JSON with Comments" and abbreviated as "jsonc".
+ "jsonc" is not JSON, but rather a superset of JSON that adds support for comments.
```

This is common for config files, such as:

- all VS Code config files
- deno.json
- appsettings.json (ASP.NET)

[How VS Code describes it:](https://code.visualstudio.com/docs/languages/json#_json-with-comments)

> When in the JSON with Comments mode, you can use single line (//) as well as block comments (/* */) as used in JavaScript. The mode also accepts trailing commas, but they are discouraged and the editor will display a warning.

IMO, trailing commas are out of scope for this issue, but I don't feel strongly about that.

### Concrete use case

Say I want to enforce in CI/pre-commit that certain config parameters aren't being used. I can't use `jaq` for this today because my settings files almost always have comments, including ones for this use case:

```jsonc
{
    // ...
    "rust-analyzer.cargo.features": "all",
    "rust-analyzer.check.command": "clippy",
    // ...
    "prettier.enable": true // the only prettier setting allowed
    /*
        Reminder: code formatting rules do not belong in vscode settings files,
        because they don't play nicely with other editors and CI jobs.

        In other words, don't add rules like:

        "prettier.useTabs": false

        Instead, use .prettierrc.yaml to change formatting rules.
    */
    // ...
}
```

If `jaq` were able to parse this file (ignoring the comments), I could use a CI/pre-commit script like this: 

```jq
jaq --exit-status '
  .
    | del(."prettier.enable")
    | with_entries(select(.key | startswith("prettier")))
    | length == 0
' ".vscode/settings.json"
```

### Dead Ends

- I checked for previous issues/discussions about this and didn't find anything.
- I considered using `rg`/`sed` to strip comments before passing to `jaq`, but this is difficult to get right.
- I found some tools that purport to strip comments, but nothing stood out as easy/popular/well-tested/safe. Arguably I should look more deeply into those options. I'm open to suggestions!
- I started to implement this `jaq` feature myself. I added some failing tests but didn't get far before realizing I should open an issue to discuss it. Plus, while editing `hifijson`, I noticed that the `jaq` branch, [`faster-lexer`](https://github.com/01mf02/jaq/tree/faster-lexer), is being actively developed as of July 2024, so I worried that adding to `hifijson` could be a mistake. I see that branch now has a PR (https://github.com/01mf02/jaq/pull/196) -- perhaps that's only for parsing input expressions, not JSON input?

**Comment by 01mf02** [comment]
Hi @denosaurtrain! Thanks for taking your time to explain me your use case in such a detailed way!
Your suspicion in your last "dead end" is dead on --- the `faster-lexer` branch is for parsing/lexing jq programs, not JSON input. To allow jaq to parse JSON comments, modifying `hifijson` is the way to go. If you make a PR to `hifijson`, I am very much open to incorporate such a change.

**Comment by 01mf02** [comment]
I have read a bit about comments in JSON since my last message, and I have gained a different opinion in the meantime. In particular, I'm now more skeptical about allowing comments in JSON. In discussions like [on Stack Overflow](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json), there is a relatively strong consensus that comments should not be present in JSON, and if one wants to put in comments nonetheless, they [can be removed for further processing](https://web.archive.org/web/20190112173904/https://plus.google.com/118095276221607585885/posts/RK8qyGVaGSr) (that's what you called your dead end no. 3).

I tried `jsmin` by the JSON author (Douglas Crockford), and it seems pretty simple to me: Go to https://github.com/douglascrockford/JSMin, download jsmin.c, run `gcc jsmin.c -o jsmin`, then `./jsmin <input.json | jaq .` and you're good to go. Wouldn't that satisfy your needs of a tool that is easy/popular/well-tested/safe?

**Comment by pkoppstein** [comment]
@denosaurtrain - Another possibility for pre-processing is https://hjson.github.io/

@01mf02  - Since there are tools that strip comments from JSON, the horse is already out of the barn, so on balance I think it would probably make the world a better place if tools like jq/jaq had an option that would allow comments or at least one form of comments.  Since jq and jaq do allow "#" comments in JSON that is presented as (part of) a jq/jaq program, my hope is you will get the ball rolling and add an option that would at least allow them.  Not the highest priority by any means, of course, but maybe worth. re-opening this issue.

**Comment by 01mf02** [comment]
I'm happy that jsmin works for you. I think that there is value in sticking to the most widely recognised definition of what JSON is, and that is the spec. Everything else opens a pandora's box, IMO.

Just for completeness: In the future, I think that the road forward will be for jaq to support YAML. That would allow not only for comments, but also for other syntax that JSON does not offer. jaq 1.5 has removed the roadblocks to support different input formats in jaq, it now "only" remains to integrate a YAML parser with jaq, define the operations on YAML values, and you got YAML support (and with that basically JSON with comments for free).

**Comment by 01mf02** [comment]
Just to be clear, when I say that jaq supports YAML, that means that it should provide a mode where it reads input data as JSON and another where it reads input data as YAML.

**Comment by 01mf02** [comment]
I have come across JSON5, which is a fairly popular JSON extension (including comments) with a proper specification.
Furthermore, it comes with a tool to convert JSON5 to JSON, which would also allow you to write comments in JSON:
 https://github.com/json5/json5

**Comment by 01mf02** [comment]
> Unlike adding `YAML` support, which requires a separate code path and/or library, `jsonc` is _so close_ to JSON that, as an implementation detail, the simplest implementation is a JSON parser with an opt-in flag to ignore comments. I.e., it becomes a parser that supports two formats: either JSON or `jsonc`.

I also thought that `jsonc` is _so close_ to JSON that it would be simple to have a flag somewhere that regulates whether comments are ignored or errors. Then I looked a bit closer at the implementation of the library that underlies JSON parsing in jaq, `hifijson`: [This line](https://github.com/01mf02/hifijson/blob/9fb43ee07ba170891bc8fd663dfe9f99e926dea9/src/token.rs#L98) would need to be modified. Unfortunately, due to the architecture of `hifijson`, in this function, it is not easy to "just" introduce a flag (in a nutshell, because this function is in a trait, and a trait does not have associated data, so we cannot easily store something here). This can be solved, but (a) it would require quite a bit of new code, and (b) it might have a negative performance impact on JSON parsing without comments. That's why I'm not so keen on integrating optional JSONC support into `hifijson`, especially when this use case can be addressed either with tools like `jsmin` or once jaq supports YAML. I hope you understand.

**Comment by 01mf02** [comment]
> Absolutely! You've been extraordinarily patient with my long, pedantic posts.

It's my pleasure. I think it is important to explain the reasoning behind decisions to gain acceptance for them.

> Indeed. YAML won't help me because I'm forced to use `jsonc`, but with `jsmin` I can do things like this:

Ah, I was under the misconception that YAML supported block comments --- in that case, you could just have interpreted your JSONC file as YAML and everything would have worked. Too bad that this is not the case. :(

Well, at least I'm happy that your jsmin workflow now works. :)
