### ISSUE TITLE
jaq ignores multiline (`m`) flag in regex operations

### ISSUE THREAD

**Issue by just-max** [01mf02/jaq#201]
Best seen with an example, tested on latest main commit (https://github.com/01mf02/jaq/commit/544fd9af800d641f1b244d1fe000d1b3333b6811):

Without multiline:
```text
$ echo '"string\nwith\nlinebreaks"' | jaq 'match("(?<g>.*)") | .captures | .[] | .string'
"string"
```
> *OK*

With multiline, output should be `"string\nwith\nlinebreaks"`
```text
$ echo '"string\nwith\nlinebreaks"' | jaq 'match("(?<g>.*)"; "m") | .captures | .[] | .string'
"string"
```
> *not OK*

For comparison, `jq` (latest commit, `jq-1.7.1-60-gc1d885b`):

```text
$ echo '"string\nwith\nlinebreaks"' | jq 'match("(?<g>.*)"; "m") | .captures | .[] | .string'
"string\nwith\nlinebreaks"
```
> *expected behaviour*

**Comment by 01mf02** [comment]
Hi Max, there seems to be a bigger confusion regarding jq regex flags: https://github.com/jqlang/jq/issues/2663
For your use case, you could try the `p` flag instead of `m`.

**Comment by 01mf02** [comment]
For the reference, jaq interprets the regex flags `m` and `s` like [Perl](https://perldoc.perl.org/perlre#Modifiers); that is, `s` makes `.` match newlines, and `m` makes `^` and `$` match the beginning and end of each line, respectively (instead of only matching the beginning and end of the whole string).
For this, jaq uses the functions [`multi_line`](https://docs.rs/regex/latest/regex/struct.RegexBuilder.html#method.multi_line) for `m` and [`dot_matches_new_line`](https://docs.rs/regex/latest/regex/struct.RegexBuilder.html#method.dot_matches_new_line) for `s`.

**Comment by 01mf02** [comment]
It seems that you can also set the `s` flag inline:

~~~
$ echo '"string\nwith\nlinebreaks"' | jq-linux-amd64-1.7.1 'match("(?s:.*)"; "")'
{
  "offset": 0,
  "length": 22,
  "string": "string\nwith\nlinebreaks",
  "captures": []
}
~~~

That yields the same results for both jq and jaq.

**Comment by just-max** [comment]
Thanks! Then `s` does what I need from `jaq`, I just got tripped up by referencing the `jq` docs. If I need a filter compatible with both, I will use the inline flag as suggested.
