### ISSUE TITLE
More compatible `debug/0` and add `debug/1`

### ISSUE THREAD

**Issue by wader** [01mf02/jaq#213]
I noticed that `debug/1` is missing and that `debug/0` behaves as bit diffetenrtly compared to other jq implementations, they output `["DEBUG", <value>] lines` on stderr, which is quite nice as you can then use jq again to filter and transform the debug output. Also it would improve on compatibility between implementations.

I tried to implement it myself but ran into issues quite fast, ex i guess the jaq-std code should not use stderr directly? and it also would need access to current color config i think? how to pass along such stuff to a filter? i could give it a try again with some guidance.

**Comment by 01mf02** [comment]
Good morning @wader. Thank you for your suggestion.
I took the liberty to implement the first part of your issue, namely a more compatible `debug/0`, in b71ea96e50b028283c27cbf90f2159a7d4001b38. It made more sense to do this myself because I already knew where to look.

If you wish to have a little challenge, I let you implement `debug/1` yourself. I would go about it by modifying the implementation of `debug/0` to `debug/1`, then implement `debug/0` by definition via `debug/1`.

**Comment by wader** [comment]
Morning! what do you think about adding `stderr/0` (exists in jq) and the do something like:
```jq
def debug(f): ((["DEBUG", f] | tojson), "\n" | stderr | empty), .;
def debug: debug(.);
```
I tried to do it but got lost in the logging infra that seems to always format so ended up with quoted/escaped strings :( would it make sense to expose some kind of abstract raw stdout/stderr to filters?

**Comment by 01mf02** [comment]
Concerning `stderr/0`: This is a good addition, I added it myself just now.
Still, I think that `debug` should not be defined in terms of `stderr`: First, this adds some overhead (by creating an additional string). Second, it excludes using `debug` in environments like jaq-play (WASM), where there is no `stderr`, but there may be some log handler such as [`console_log`](https://docs.rs/console_log/latest/console_log/).

I took the liberty to implement `debug/1` now myself, because I also remade `error/1` at the same time.

**Comment by wader** [comment]
Great! so that i follow, so with these changes both `stderr/0` and `debug/*` will be available in jaq-play?

**Comment by 01mf02** [comment]
> Great! so that i follow, so with these changes both `stderr/0` and `debug/*` will be available in jaq-play?

No. `stderr/0` will not have any effect (because there is not standard error output on the web). `debug/*` will have an effect as soon as 2f54da3 is deployed. :)
That's what it looks like:

![console-log](https://github.com/user-attachments/assets/7d7bb17f-f7ec-4e09-981f-b6252226df74)

**Comment by wader** [comment]
Aha it gets mapped to `console.debug()`? could `stderr/0` map to `console.error()`? 🤔 but i guess that would break the no-new-line behaviour

**Comment by 01mf02** [comment]
@wader, this is a pretty good idea! Thanks to your remark about `console.error()`, I had an idea how to enable `stderr` on jaq-play: While it is not a good idea to directly write to `console.error()` in jaq-std (because it means that jaq-std would gain a pretty heavy dependency on browser APIs), we can yield the same effect by using the `log` crate similarly to `debug`. When executing `stderr`, we just call `log::error!`. For the jaq CLI, we then have to customise how the error is printed (in `jaq/src/main.rs`). For WASM, we then have to do nothing at all --- `console_log` calls `console.error()` for us! See 7c24e9dbffc93fbbb2f790b78ae9a781ecb2fef7 for details.

![Screenshot_2024-09-26_09-33-38](https://github.com/user-attachments/assets/ae5fdf6e-d446-41a9-86eb-42d1d79e9e49)
