### ISSUE TITLE
Inconsistencies in jaq date formatting in versions 1.3 and 1.6

### ISSUE THREAD

**Issue by bedilbek** [01mf02/jaq#214]
```shell
jaq --version
jaq -nc '"2024-05-15T15:38:00.200Z" | fromdate | todate'
jaq -nc '"2024-05-15T15:38:00.000Z" | fromdate | todate'
```
![image](https://github.com/user-attachments/assets/dace23b9-5a39-468a-b2b8-42c6c6bc5da3)

![image](https://github.com/user-attachments/assets/113f9eb8-195a-4e11-b48f-9f187662006a)

**Comment by bedilbek** [comment]
I would rather backport those date formatting as it was in version 1.3.0. Because I believe that formatting was more consistent and deterministic

**Comment by 01mf02** [comment]
Hi @bedilbek, you're right, the jaq 1.6 behaviour does not seem to be very consistent.
This was due to a bug; I thought that for a floating-point number `f`, `f / 1e6` is equivalent to `f * 1e-6`; it turns out that the former (division) preserves more precision than the latter (multiplication).
I also fixed the precision of `todate` to always print 6 decimal places if the input is a floating-point number. This should also contribute to making the formatting more consistent.
Again, thanks for spotting and reporting this!
