### ISSUE TITLE
Crash on modulo operator with 0

### ISSUE THREAD

**Issue by itchyny** [01mf02/jaq#25]
Currently `jaq` crashes on modulo operator if the right hand side is 0. It should report an error (or emit nan).
```
 $ jq -n '0 % 0'
jq: error (at <unknown>): number (0) and number (0) cannot be divided (remainder) because the divisor is zero

 $ jaq -n '0 % 0'
thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', jaq-core/src/val.rs:382:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by 01mf02** [comment]
Well spotted.
I considered three potential outputs:

* nan: It feels like this should be reserved for floating-point operations, which modulo (currently) is not.
* null: Sounds a bit dangerous to return this, because the result of a modulo might be added to some other value.
* error: Seems like the least intrusive option and is in line with Python and Rust.

So error it is. Corrected in c272b59. Thanks!
