### ISSUE TITLE
add a `not(condition)` ?

### ISSUE THREAD

**Issue by tst2005** [01mf02/jaq#37]
Hello,
I'm using jq for years but I just discovered jaq today.

I remember a detail that I have thought about and forgotten so often...

When I read 
```jq
def isnormal:   isnumber and ((. == 0 or isnan or isinfinite) | not);
```
I think "isnumber and ( is zero or nan or infini) ... oh wait ! the condition is the opposite ! but from where ?"
And I read again to find the proper parenthesis and check again the double parenthesis...

I think it could be easier to read/understand with a `not(condition)` instead of `condition|not` syntax.

```jq
def isnormal:   isnumber and not(. == 0 or isnan or isinfinite);
```

My goal is not to include a `not(condition)` function only to patch isnormal (I took it as sample) but to let it available for any thirdparty code.

I don't know if the `not(condition)` can have a performance impact.

Feel free to make your feedback!

**Comment by 01mf02** [comment]
Hi @tst2005, I understand your use case. However, I think that by your reasoning, one could also define lots of other such filters;
for example, instead of `0 | isnan`, one might want to write `isnan(0)`. Same for `tostring`, `type`, ...
In general, every filter that takes no arguments could be made into a filter with one argument.
However, because jaq aims to have a small implementation, I am against introducing such filters.
I hope you understand.

**Comment by tst2005** [comment]
no problem, I understand
