### ISSUE TITLE
Question about parallel processing

### ISSUE THREAD

**Issue by universalmind303** [01mf02/jaq#45]
I'm playing around with the jaq_core module to see if i can integrate it into a project, and I noticed that you are using single threaded `Rc`. I'm wondering what the design decisions behind this was? It seems to me that a lot of the processing could likely be done in parallel via `rayon` & `.par_iter()`. 

Would you be open to some contributions to allow parallel processing?

**Comment by 01mf02** [comment]
Hi @universalmind303!
The reason behind using `Rc` in `Filter`s is that it allows for fast construction of strings:
Because `Val` uses `Rc<String>` to represent strings, keeping `Rc<String>` in `Filter` allows us to construct string values in constant time, using `Rc::clone`.
Before, I just used `String` in `Filter`, but this implies overhead whenever we create a string value from a string filter.

As an example, consider the filter `{"a": .[]}`: When storing the `"a"` in the filter as `Rc<String>`, executing this filter will keep only a single copy of `"a"` in memory, whereas storing the `"a"` in the filter as `String`, executing this filter will create `n` copies of `"a"` in memory (where `n` is the length of the input array).

I see two ways to avoid using `Rc` in `Filter` and to make it thread-safe:

1. Use `Arc<String>` in `Filter` and `Val`: I am not happy about this, because it is slower than `Rc`.
2. Use `String` in `Filter` and `Rc<String>` in `Val`: This is probably a bit faster than `Arc`, but still, it makes more string copies, as shown in the example above.
3. Use `&str` in `Filter` and add a variant for `&str` in `Val` (different from `Rc<String>`): This is probably the fastest option, but it comes at a high price of implementation complexity, because it introduces lifetimes for `Val`.

If you have another idea, let me hear it. Also, if you wish to try one of the solutions I outlined, I would be happy about some benchmarks how they influence string performance. I suppose that option 2 would be still relatively fast.

**Comment by 01mf02** [comment]
And if you find a solution that is both fast and does not make the code much more complicated, I would be happy to integrate it! :)

**Comment by 01mf02** [comment]
Ok, I benchmarked the performance of `String` compared to `Rc<String>` in `Filter`, and the difference is neglectable. Therefore, I went ahead and made `Filter` use `String` instead of `Rc<String>` (8201559172660b009d75c0c7f8caa05225fd4385), making it thread-safe and therefore compatible with parallel processing.
When processing multiple `serde_json::Value`s, just convert them to a `jaq_core::Val` inside a thread, then convert the result back to `serde_json::Value` in the same thread. Then you should be good to go. Let me know if you need some help with parallel processing.

**Comment by universalmind303** [comment]
@01mf02 Not necessarily related to parallel processing, but have you considered alternative json parsers. You are using a custom `Val` anyways, so I dont think there is a strong dependency on `serde_json`. As a test, I switched over `jaq` to use [json-deserializer](https://github.com/jorgecarleitao/json-deserializer) and saw a pretty massive performance boost reading data with lots of strings. 

For example, one dataset I commonly test with took `4.31` sec using serde_json for the parser, and `1.79` with json-serializer. I'd be happy to share the dataset I was using for testing, as well as the fork with the code changes if you are interested in taking a look.

**Comment by 01mf02** [comment]
@universalmind303: I would be very interested in your fork with the fork changes! I would also accept a PR from you.
