### ISSUE TITLE
create `jaq_std::Definitions` which includes std definitions, similar to `jaq_core::Definitions`

### ISSUE THREAD

**Issue by award28** [01mf02/jaq#68]
First off, thanks for this project!

~Some of the functionality which is currently behind the `jaq` binary crate are [copied/pasted by users](https://github.com/search?q=jaq_std&type=code) to recreate the functionality. Given this, it seems like some of these methods should be moved to the `jaq_std` library crate. One such method would be the [parse](https://github.com/01mf02/jaq/blob/main/jaq/src/main.rs#L237) method, which includes the std library definitions as well as the core definitions.~

I misunderstood what I needed to do in order to get std definitions integrated with the core definitions. It's pretty straightforward, but I still think something akin to the `jaq_core::Definitions` could be helpful to have in the std library for anyone who wants to use jaq in code rather than the CLI.

**Comment by 01mf02** [comment]
I am currently overhauling the filter definition API as a part of supporting recursive and nested definitions, so I will try whether I can make adding the standard library nicer.

**Comment by award28** [comment]
@01mf02 thank you! If you would there are any issues you would like help with, I'm happy to contribute.

**Comment by 01mf02** [comment]
I have now changed the API so that you can do:

    defs.insert_defs(jaq_std::std(), &mut errs);

This should be easier to use.

Currently, the biggest help would be to torture jaq with recursive and nested filters, because I just implemented some support for this, which is still rough around the corners. If you find some recursive/nested filters that do not work as expected, filing an issue would be a big help. Or even if you have some interesting filters that *do* work, submitting tests for these would be good as well. af64f3ec8e8ef76bc23861142b2fe2a1d4de731c shows a few tests in a new format that I introduced today which should make it easier to write new tests.

**Comment by pkoppstein** [comment]
> the biggest help would be to torture jaq with recursive and nested filters

I've just updated the [jq entry](https://rosettacode.org/wiki/Ramsey%27s_theorem#jq) in the "Ramsey's theorem" page at rosettacode.org so that the program now runs under jaq (or at least b135078), with the
minor exception of having to fiddle with the line that uses string interpolation.

So, first, a big thank you!

Second, congratulations!

And third, a request that you consider enhancing jaq so that the string interpolation annoyance goes away.

**Comment by pkoppstein** [comment]
> the biggest help would be to torture jaq with recursive and nested filters

Below is a straightforward def of Ackermann's function, with
a "debug" statement to keep track of the recursion depth.
Using jq or gojq, ack(2,2) produces 27 DEBUG lines, along with the correct answer.

jaq, by contrast, goes in circles, and eventually ends with
<pre>
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
</pre>
Note that splitting the `ack($m-1; ack($m; $n-1))` line into two steps does not help.
```
def ack($m;$n):
  ([$m,$n] | debug) as $d |
  if $m == 0 then $n + 1
  elif $n == 0 then ack($m-1; 1)
  else ack($m-1; ack($m; $n-1))
  end ;
```

**Comment by wader** [comment]
Maybe some of these can be interesting test cases:

https://github.com/stedolan/jq/blob/master/tests/jq.test#L589-L649
https://github.com/wader/jqjq/blob/master/jqjq.test#L341-L411
https://github.com/itchyny/gojq/blob/main/cli/test.yaml

**Comment by 01mf02** [comment]
@pkoppstein, I found and squashed two bugs in the implementation of recursive functions in jaq, and now the Ackermann function yields correct values.

**Comment by 01mf02** [comment]
> First, thank you for you work on this so far. Very impressive.

Thank you! :)

> Second, in accordance with your request above, I revised the [jq program](https://rosettacode.org/wiki/Ramsey%27s_theorem#jq) in the "Ramsey's theorem" page at rosettacode.org so that it now runs under jaq (or at least [b135078](https://github.com/01mf02/jaq/commit/b135078433781b6b6d85e64759b4616f67763382)), with the minor exception of having to fiddle with the line that uses string interpolation. However the result is wrong.

My bug squashing effort has made it work as well:
At least [the version without string interpolation](https://github.com/01mf02/jaq/files/11225155/ramsey.txt).

> Please also consider enhancing jaq so that the string interpolation annoyance goes away.

I do not feel motivated enough to work on this feature. On the other hand, if somebody wishes to implement it, I would be happy to accept a PR.

**Comment by pkoppstein** [comment]
@01fm02 wrote:
> My bug squashing effort has made it work as well.

Fantastic!  I've updated the Ramsey Theorem and Ackermann function pages on
rosettacode.org to reflect these latest enhancements.

It would really help to have a version number attached to a version
of jaq which handles Ackermann's function correctly :-)

**Comment by 01mf02** [comment]
> Fantastic! I've updated the Ramsey Theorem and Ackermann function pages on
> rosettacode.org to reflect these latest enhancements.

Thank you! Could you perhaps just convert the string interpolation to string concatenation on the Ramsey Theorem so that the example works with all current jq implementations? 

~~~
-   | "Totally \($cs)connected group: " + (.idx | map(tostring) | join(" "))
+   | "Totally " + $cs + "connected group: " + (.idx | map(tostring) | add)
~~~

> It would really help to have a version number attached to a version
> of jaq which handles Ackermann's function correctly :-)

This should be now the case with jaq 1.0.0-alpha. :)
