### ISSUE TITLE
def foo(E): ... foo(E) ...;

### ISSUE THREAD

**Issue by pkoppstein** [01mf02/jaq#73]
jq and PEGs (Parsing Expression Grammars) have a very close affinity
that is pehaps most clearly seen by the correspondence between the 
classic PEG operators (* + ? & !) and their counterparts defined in jq as follows:
```
def star(E): (E | star(E)) // . ;
def plus(E): E | (plus(E) // . );
def optional(E): E // .;
def amp(E): . as $in | E | $in;
def neg(E): select( [E] == [] );
```
The first two of these are of course recursive, and
are handled properly by both jq and gojq,
but cannot currently be handled by jaq.

I was hoping that jaq might be able to handle
the special form of recursion seen here, namely
where foo(E) is defined in terms of foo(E)

**Comment by 01mf02** [comment]
The reason why I will not support this special form of recursion is because it is very easy to introduce performance problems this way, without noticing it at first.
Take as example the following filter:

    def rep(a): a, rep(a);

This looks quite harmless, right? It just repeats the output of the filter `a`.
But actually, we introduced a performance bottleneck --- this takes exponential time to evaluate:

    jq -n 'def rep(a): a, rep(a); limit($N; rep(1)) | empty'

Try to vary $N; for n = 5000, 10000, 20000, jq takes 1.0s, 3.9s, and 16.0s! Clearly exponential.

I am quite certain that the same problem occurs also with `star(E)` and `plus(E)`.

Now how about:

    jq -n 'def rep(a): def rec: a, rec; rec; limit(20000; rep(1))'

It takes 0.2s. It is functionally equivalent to the filter above, but it is much faster. And it is supported by both jq and jaq.

**Comment by 01mf02** [comment]
My philosophy behind this is: rather than providing tools that are likely to turn out to be footguns, better not provide them at all. In the end, this gives you more confidence in the tools you have.
